### PR TITLE
Improves the UI Level0/SendToEather

### PR DESCRIPTION
**Pull request by ankur0904**
Screenshot from 2022-09-16 23-23-24

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
@ankur0904  please resolve the conflict

**Comment by ankur0904** [comment]
I am unable to resolve the conflict. Can you please help me in this?

**Comment by Vikash-8090-Yadav** [comment]
ok wait .
Update the readme also . Add  the images with the brief description .

**Comment by Vikash-8090-Yadav** [comment]
@ankur0904  wait am checking

**Pull request merged**
