### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Durgesh4993**

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Gr8  , Lookiing forward to see more contribution from your side .

**Comment by Durgesh4993** [comment]
Please suggest me in which project i will work

**Comment by Vikash-8090-Yadav** [comment]
@Durgesh4993 sorry forate responsive , i just saw ur comment , if u are familiar with web3 then try to build full stack website based on web3 , full stack crowd funding dapp , u can also make ur own voting application dapp , all these tutorial are avilable on youtube ✌️.
Best of luck 🤝

**Comment by Durgesh4993** [comment]
yes sir deffinetly i love to work with you

**Pull request merged**
