### PR TITLE
another frontend project

### PR DESCRIPTION
**Pull request by targithu**

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Raise an issue first for this . 
Thank u :smile:

**Comment by Vikash-8090-Yadav** [comment]
Create a readme for both the project's . 
The readme should contains . 
1. Heading 
2. About the project 
3. Images 
4. running video 
 Feel free to comment if u feel any doubt .

Happy open source :smile:

**Comment by Vikash-8090-Yadav** [comment]
issue #109

**Comment by targithu** [comment]
@Vikash-8090-Yadav now I have added the Readme files as well

**Comment by Vikash-8090-Yadav** [comment]
Looking Great to me .thank for oontributing in my repo.Looking forward to see more from your side. 
Happy open source ☺️

**Pull request merged**
