### PR TITLE
Write a Blog post on Ethereum killers

### PR DESCRIPTION
**Pull request by GloriaOkeke**
Just added a helpful blog post about Ethereum killers

### CODE REVIEW

**Comment by GloriaOkeke** [comment]
Hi @Vikash-8090-Yadav I'm done with this. Kindly review and merge

**Comment by Vikash-8090-Yadav** [comment]
@GloriaOkeke  i guess ur images and all the extra style is not visible like # and images . please check once and make  it correct

**Comment by GloriaOkeke** [comment]
@Vikash-8090-Yadav I just effected some change. please let me know if that's right.

**Comment by Vikash-8090-Yadav** [comment]
Please check the folder  in which  u have  putted . I guess u putted in the wrong folder , 
OK , do one  thing close this  pr . Delete my repo from your computer and again clone this and make new folder inside the Blog folder named "Ethereum Killers" then in that folder include readme.md and write about your blog . I hope u  understand . .

Let me know if u need any help !
Thank u  :smile:

**Comment by GloriaOkeke** [comment]
Alright got this

**Pull request closed without merging**
