### PR TITLE
Adds project ideas

### PR DESCRIPTION
**Pull request by ankur0904**
Added the file in which there are some of the projects ideas are present.

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
U don't need to add the files in the Project section . Please add some project  name and   their work .

**Comment by ankur0904** [comment]
Yes, I only added the name of the project in .txt file.

**Comment by Vikash-8090-Yadav** [comment]
Are u still working on this issue ?

**Comment by Vikash-8090-Yadav** [comment]
Closing in preparation for other Open source Programme .

**Pull request closed without merging**
