### PR TITLE
Created a decentralized domain name market place. issue no #161

### PR DESCRIPTION
**Pull request by Kaushan-Dutta**

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
It's looking gr8 , but write something about your project in readme and add some images also .

**Comment by Vikash-8090-Yadav** [comment]
And please tell me your issue number also .

**Comment by Kaushan-Dutta** [comment]
> And please tell me your issue number also .

#161

**Comment by Kaushan-Dutta** [comment]
> It's looking gr8 , but write something about your project in readme and add some images also .

yes, sure I will do it

**Comment by Kaushan-Dutta** [comment]
> It's looking gr8 , but write something about your project in readme and add some images also .

I have made the changes, just check it

**Comment by Vikash-8090-Yadav** [comment]
Gr8 , Looking forward to see more contribution from your side !!

**Pull request merged**
