### PR TITLE
Readme file

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
@Vikash-8090-Yadav 

Created README.md file for each level and i have described the projects in a systematic manner . If your find it good then please merge it sir or else if any change required then also please comment

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
attach the images also

**Comment by Bharadwajshivam28** [comment]
> attach the images also

Ok sir  I will add images

**Comment by Bharadwajshivam28** [comment]
Attached the images and also live working videos @Vikash-8090-Yadav

**Comment by Vikash-8090-Yadav** [comment]
@Bharadwajshivam28 remove the videos.

**Comment by Vikash-8090-Yadav** [comment]
@Bharadwajshivam28 update the level0 , as the level contains the 5 projects and  in your updated readme it shows only 4

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 remove the videos.

ok sir

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 update the level0 , as the level contains the 5 projects and in your updated readme it shows only 4

oh sorry sir it will be updated

**Comment by Bharadwajshivam28** [comment]
Updated these sir

**Comment by Vikash-8090-Yadav** [comment]
attach  only one image / screen shot for the particular project decsription .

**Comment by Bharadwajshivam28** [comment]
> attach  only one image / screen shot for the particular project decsription .

Sir please elaborate

**Comment by Bharadwajshivam28** [comment]
> attach  only one image / screen shot for the particular project decsription .

Ok sir

**Comment by Bharadwajshivam28** [comment]
@Vikash-8090-Yadav Done with the changes sir

**Comment by Bharadwajshivam28** [comment]
@Vikash-8090-Yadav Hello sir if no issue then please merge it sir

**Pull request closed without merging**
