### PR TITLE
Update For Send-To-Ether (HTML -file)

### PR DESCRIPTION
**Pull request by Durgesh4993**

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Ping me when  u r done .

**Comment by Durgesh4993** [comment]
yes sir i have completed or want to suggest me something

**Comment by Vikash-8090-Yadav** [comment]
Paste the ss also in the PR

**Comment by Durgesh4993** [comment]
image

**Comment by Vikash-8090-Yadav** [comment]
GR8   ,  looking forward to see more  contribution from your side .

**Pull request merged**
