### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by Mohammed-Shoaib01**
Hey, noticed there was no Code of Conduct. 

Hope this helps!

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Hey @Mohammed-Shoaib01  . Thanks for this ,  this really helps me as well as lot's  of the contributor . 
Just do  one thing , please raise a issue for this as making direct  pr is not good practice and it  dis respect our guidelines . 
and also add that issue no in this pr. 
Hope  u understood . 
Happy opensource . :smile:

**Comment by Mohammed-Shoaib01** [comment]
My bad, on it right now!

**Comment by Mohammed-Shoaib01** [comment]
Hey @Vikash-8090-Yadav just added issue #78, wasn't sure if adding the issue number like this is okay, please advice!

**Comment by Vikash-8090-Yadav** [comment]
Ya this is ok . @Mohammed-Shoaib01 

But most of these things like issue no all are added in the Starting of creating PR only . 
but no worries , should remember time .
🙂

**Comment by Mohammed-Shoaib01** [comment]
Okay! Got it!

**Comment by Mohammed-Shoaib01** [comment]
Hey @Vikash-8090-Yadav, do you need me to make any changes?

**Comment by Vikash-8090-Yadav** [comment]
LGTM . Thanks for your readme look''s clean and nice . 
Looking forward for  more contribution from your side . 

Happy  opensource 
:smile:

**Comment by Vikash-8090-Yadav** [comment]
@Mohammed-Shoaib01 Please update your branch to the latest  .

**Comment by Mohammed-Shoaib01** [comment]
@Vikash-8090-Yadav Does this work?

**Comment by Vikash-8090-Yadav** [comment]
Yes :+1:

**Pull request merged**
