### PR TITLE
updated the index.html

### PR DESCRIPTION
**Pull request by GitWiz01**
corrected typo and solved amount field input problem

### CODE REVIEW

**Comment by GitWiz01** [comment]
@Vikash-8090-Yadav sir i have solved the problems. kindly let me know if any more changes are to be done. 🙂

**Comment by Vikash-8090-Yadav** [comment]
@GitWiz01  please share the ss of the changes u have done .

**Comment by GitWiz01** [comment]
@Vikash-8090-Yadav 
now only numers can be filled in amount section
corrected typo in 
ether1
ether

**Comment by GitWiz01** [comment]
@Vikash-8090-Yadav Sir if you find the commits appropriate please add iwoc and difficulty level tag on this pr and merge it .

**Pull request merged**
