### PR TITLE
New readme.md file for level 0 folder and all the grammatical errors solved.

### PR DESCRIPTION
**Pull request by AnmolSirola**
## Description

New readme.md file for level 0 folder and all the grammatical errors solved.

Fixes #<20>

## Type of change

- [x] Documentation

- [x] Improve the readme of any project

## Domain of Contribution

- [x] Project Test on the Remix IDE

## Checklist ✓

- [x] I'm SSOC'22 contributor

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
@AnmolSirola  u cant do this  like solidity-pathshala repo , U have to run the code in your local system and then take the screen shot from that section .
Hope its clear now !Feel free to message me if u have any query 
Thank u !!

**Comment by AnmolSirola** [comment]
Ooo... My bad I will correct it right now . Thanks

**Comment by AnmolSirola** [comment]
Sir, Can u check it now I have made the required changes

**Comment by Vikash-8090-Yadav** [comment]
just check the voting appliaction for  this repo u  have to make the running video . @AnmolSirola  
if u r facing any doubt feel free to msg  me ...

**Comment by AnmolSirola** [comment]
The running video of voting application is already present in the voting folder.

**Comment by Vikash-8090-Yadav** [comment]
> The running video of voting application is already present in the voting folder.

I am talking about send to ether ..file
@AnmolSirola

**Comment by AnmolSirola** [comment]
Ohh.. sorry I misunderstood the sentence. Yes, I will run it on my system and make a running video of sendether.

**Comment by AnmolSirola** [comment]
Sir, I have fixed all the issues which I have written in my description but I need help with the video thing coz the code is not working on my system.

**Comment by Vikash-8090-Yadav** [comment]
@AnmolSirola  update your branch to the latest first .

**Pull request closed without merging**
