### PR TITLE
Added README file in each level

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
Sir i have deleted old repo and forked again and completed the README part

### CODE REVIEW

**Comment by Bharadwajshivam28** [comment]
PLease add the medium tag and iwoc tag also sir if it is not

**Comment by Vikash-8090-Yadav** [comment]
Add only one image in each level .

**Comment by Bharadwajshivam28** [comment]
ok sir

**Comment by Bharadwajshivam28** [comment]
@Vikash-8090-Yadav Done with the changes sir

**Comment by Bharadwajshivam28** [comment]
@Vikash-8090-Yadav if it is ok then can it be merged and closed sir?

**Comment by Vikash-8090-Yadav** [comment]
Remove the second  image of the voting project

**Comment by Bharadwajshivam28** [comment]
> Remove the second  image of the voting project 

Ok sir

**Comment by Bharadwajshivam28** [comment]
@Vikash-8090-Yadav  Done with  it sir

**Comment by Vikash-8090-Yadav** [comment]
add the images in level 1 folder   in which u haven't added

**Comment by Bharadwajshivam28** [comment]
ok sir

**Comment by Bharadwajshivam28** [comment]
sir can i get images as there is no images for some projects @Vikash-8090-Yadav

**Comment by Bharadwajshivam28** [comment]
@Vikash-8090-Yadav Sir there are many projects which dont have images they have videos so can you drop the iamages of those projects

**Comment by Vikash-8090-Yadav** [comment]
can u please tell the project name  for  which u want images  ?

**Comment by Bharadwajshivam28** [comment]
> hey @Bharadwajshivam28  thanks for the patience  , wait i ll provide u the images soon  

Ok sir

**Comment by Bharadwajshivam28** [comment]
@Vikash-8090-Yadav And also drop some pictures of more i am giving ss

**Comment by Bharadwajshivam28** [comment]
Screenshot from 2023-02-20 21-22-43

**Comment by Bharadwajshivam28** [comment]
and drop pictures of these 2 also sir and no short info is given of these 2

**Comment by Vikash-8090-Yadav** [comment]
NFT MARKETPLACE , 
nft-marketplce

and for the metanft u can run  on your local system if posible , or soon i ll send u , ost probably by tomrw.

**Comment by Bharadwajshivam28** [comment]
@Vikash-8090-Yadav MetaNFT one also sir

**Comment by Bharadwajshivam28** [comment]
@Vikash-8090-Yadav ok sir

**Comment by Vikash-8090-Yadav** [comment]
meta nft  ->
metanft

**Comment by Bharadwajshivam28** [comment]
thanks sir

**Comment by Bharadwajshivam28** [comment]
twitter dapp
staking dapp
todo dapp

**Comment by Bharadwajshivam28** [comment]
There are no images for these 3 also sir

**Comment by Bharadwajshivam28** [comment]
@Vikash-8090-Yadav Done with is\t sir

**Comment by Vikash-8090-Yadav** [comment]
for level1 take ss form the video attach . and crop the image . after that paste in level1 project whose  image is not attached ,

**Comment by Bharadwajshivam28** [comment]
ok sir

**Comment by Bharadwajshivam28** [comment]
after this any more changes sir ?

**Comment by Bharadwajshivam28** [comment]
@Vikash-8090-Yadav

**Comment by Bharadwajshivam28** [comment]
@Vikash-8090-Yadav Done with it sir

**Comment by Bharadwajshivam28** [comment]
thanks sir

**Pull request merged**
