### PR TITLE
Improved the UI and make this responsiveness

### PR DESCRIPTION
**Pull request by Durgesh4993**

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
After merge i ll check ur code  by running , if   all thing's work correctly i ll assign u the label .

**Comment by Durgesh4993** [comment]
Ok sir

**Comment by Vikash-8090-Yadav** [comment]
Can u do one thing build the readme for this .. and  debug the error that is coming in index.js in your slide show function , if there no use of this remove that function . Thanks .

**Comment by Durgesh4993** [comment]
ok sir i will remove that

**Comment by Durgesh4993** [comment]
I will propose new file where i will removed the index.js errors pr #176

**Pull request merged**
