### PR TITLE
Added a Modern NFT Marketplace

### PR DESCRIPTION
**Pull request by Syedhussainsaber**

### CODE REVIEW

**Comment by Syedhussainsaber** [comment]
Hi @Vikash-8090-Yadav , I have added all the files of the project #159. Now u can merge this into a the folder Level2/my_project__name

**Comment by Vikash-8090-Yadav** [comment]
create the better readme file for this

**Comment by Syedhussainsaber** [comment]
@Vikash-8090-Yadav  created

**Comment by Vikash-8090-Yadav** [comment]
@Syedhussainsaber  Gr8 . For now am merging this  , but please attach a running video in the  end of the readme , Gr8 work

**Pull request merged**
