### PR TITLE
A brief summary about this repo

### PR DESCRIPTION
**Pull request by AnmolSirola**
A brief summary about this repo #60

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
@AnmolSirola  Add three more points which expalins more about the level0 , lev1 and level2 folder . 
And  add some  more points to the first point  .

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav Can you check it now Sir.

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav plz look at this pr so i can create a new pr

**Comment by Vikash-8090-Yadav** [comment]
wait @AnmolSirola

**Comment by Vikash-8090-Yadav** [comment]
Well done @AnmolSirola .

**Pull request merged**
