### PR TITLE
Added Ping Pong Game 

### PR DESCRIPTION
**Pull request by Omega12Pirme**
Hey  , i have added the ping pong game . Please  have a look and let me know if u requirred any chnages . 

Readme is also coming .

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Please raise an issue first for this , Thank  u

**Comment by Omega12Pirme** [comment]
Raised an  issue : #113  .

**Comment by Omega12Pirme** [comment]
@Vikash-8090-Yadav  please have a look  on   this ,

**Comment by Vikash-8090-Yadav** [comment]
All looks great thank u for contributing in my project's

**Pull request merged**
