### PR TITLE
added all the files for the staking dapp

### PR DESCRIPTION
**Pull request by nirban256**
Created the staking dapp #50

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Create a proper readme for this file , Readme should be in the Leve1/Staking./Readme.md 
REAdme should contain the intro part ,  what u u used , how to run this  , and A proper video with  no sound .
Feel free to ask any question ,

**Comment by nirban256** [comment]
can I do it without the video?

**Comment by Vikash-8090-Yadav** [comment]
> can I do it without the video? @Vikash-8090-Yadav

Nope video is  necessary as this   project is under the  project section . So  it's mandatory . 
Hope u understand .

**Comment by Vikash-8090-Yadav** [comment]
Great work @nirban256  . Looking  forward for your more contribution.

**Comment by nirban256** [comment]
thanks

**Pull request merged**
