### PR TITLE
Login_page

### PR DESCRIPTION
**Pull request by kunal232i**
Improved the UI of the level0 -> Login_page as per the issue of #2 & #25 😄

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
@kunal232i Share the ss

**Comment by kunal232i** [comment]
> @kunal232i Share the ss

sure

**Comment by kunal232i** [comment]
Screenshot (63)
image

**Comment by Vikash-8090-Yadav** [comment]
Graet @kunal232i ..looking forward for your  more contribution

**Comment by Vikash-8090-Yadav** [comment]
@kunal232i  u haven't made the readme for this made a readme also , as well also edit the level 0 readme for the login page hope u get this !Then  i will assign u the Begineer level

**Comment by kunal232i** [comment]
> @kunal232i u haven't made the readme for this made a readme also , as well also edit the level 0 readme for the login page hope u get this !Then i will assign u the Begineer level

sure.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Tags:** Not reusable

**Pull request merged**
