### PR TITLE
added web 3.O Cover image

### PR DESCRIPTION
**Pull request by GundaSudarrshan**
I have **added the Image** so that we can use that as **cover photo** if needed 
Raise PR  Contribute

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Please add that image in the README.MD file after the **Web3.O.World** Heading written in readme file 

Screenshot from 2022-07-24 23-48-46

**Comment by GundaSudarrshan** [comment]
@Vikash-8090-Yadav  Yes I have **updated the changes in Readme.md file**

**Comment by Vikash-8090-Yadav** [comment]
Looks great :smile:

**Comment by GundaSudarrshan** [comment]
@Vikash-8090-Yadav  Have You added the HSOC Labels to the PR

**Comment by Vikash-8090-Yadav** [comment]
please check Now added .. Sorry for the inconvenience

**Pull request merged**
