### PR TITLE
Adding readme.md file in level 0 and correct all the grammatical errors

### LINKED ISSUE #20: Adding readme.md file in level 0 and correct all the grammatical errors.
### Description of  the change
The readme.md files inside folder level 0 ( sendtoEather0 ) is empty I want to fix it and fix all the existing grammatical errors (inside all the folders).

### Domain of Docs

- [x] Readme
- [x] Documentation
#### Are you contributing under any open-source program ?
SSOC'22
<hr/>

### PR DESCRIPTION
**Pull request by AnmolSirola**
# Descripion📜
Added a new readme.md file inside level 0 folder and correct all the grammatical errors.

Fixes #20 

# Type of Change 📝
please delete options that are not relevant. In order to tick the checkbox just put x inside them for example [x] like this

- [x] Modified or enchanced the existing projects
- [x] Improve the readme of any project

# Domain of Contribution 📊
- [x] Project using Solidity

# Checklist ✔

- [x] I'm SSOC'22 Contributor

### CODE REVIEW

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav Made a new pr with updated branch , can u check it now

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav Can u look at this pr plz so that I can make a pr for different issue .

**Comment by Vikash-8090-Yadav** [comment]
> @Vikash-8090-Yadav Can u look at this pr plz so that I can make a pr for different issue .

Ya sure ..checking .

**Comment by Vikash-8090-Yadav** [comment]
Great @AnmolSirola  give this P.R 5 points as u r correcting only two or three word's . Hope this seem's ok to u.  
Looking forward for your more contribution . 
Thank u :smile:

**Comment by AnmolSirola** [comment]
@Vikash-8090-Yadav No sir its fine by me :)

**Comment by Vikash-8090-Yadav** [comment]
Great @AnmolSirola

**Pull request merged**
