### PR TITLE
New

### PR DESCRIPTION
**Pull request by ankur0904**
I have improved the UI of the level0 Project.

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
@ankur0904  plaese attach the ss .

**Comment by ankur0904** [comment]
Screenshot_2022-08-10_21-16-54

**Comment by Vikash-8090-Yadav** [comment]
@ankur0904 change this pinkish colour to something else . As  the word are not seeing  properly .

**Comment by ankur0904** [comment]
Screenshot_2022-08-11_22-56-08

**Comment by Vikash-8090-Yadav** [comment]
@ankur0904  update the branch to the latest ...

**Comment by ankur0904** [comment]
ok

**Comment by ankur0904** [comment]
merged??

**Comment by Vikash-8090-Yadav** [comment]
@ankur0904 ig u haven't updatw ur branch to the latest

**Comment by Vikash-8090-Yadav** [comment]
> merged??

write git fetch in ypur terminal and update the branch

**Comment by ankur0904** [comment]
Sir, I run the command git fetch in the terminal.

**Comment by ankur0904** [comment]
Please merge it.

**Comment by Vikash-8090-Yadav** [comment]
@ankur0904  after fetching u have to  push also .. ig u haven't push that

**Comment by ankur0904** [comment]
Sir, I pushed it in terminal by git push . and after when I tried to commit then it show branch has already updated.

**Comment by Vikash-8090-Yadav** [comment]
@ankur0904 message me in the discord

**Comment by ankur0904** [comment]
Sir, I am unable to find you in discord

**Comment by Vikash-8090-Yadav** [comment]
@ankur0904  ya now its fine .. Looking forward  more contribution from  your side . 
Thank  u

**Pull request merged**
