### PR TITLE
Create Issue template #6

### LINKED ISSUE #6: Create Issue temaplate
Greetings of the day folks !!
If anyone want's to create the issue template then feel free to comment 

The issue template should contains ->  **Bug report , Feature request  and  other .**  
like shown below 

Screenshot from 2022-07-25 17-32-13

### PR DESCRIPTION
**Pull request by surjyaneeh**
fixes #6 

1. 
image

2.
image

3.
image

### CODE REVIEW

**Comment by surjyaneeh** [comment]
@Vikash-8090-Yadav kindly check it and let me know if it needs any modifications.

**Comment by Vikash-8090-Yadav** [comment]
Add all these changes .. all set to get merged :smile:

**Comment by surjyaneeh** [comment]
> Add all these changes .. all set to get merged 😄
> 
> **PS : please fetch the latest changes as your branch is behind also .**
> 
> Thank u

fetched.

**Comment by Vikash-8090-Yadav** [comment]
@surjyaneeh again its ahead of my branch ..cuz of that i am not seeing any changes . SO Please share the screen shot of the work u have done ...

**Comment by surjyaneeh** [comment]
> @surjyaneeh again its ahead of my branch ..cuz of that i am not seeing any changes . SO Please share the screen shot of the work u have done ...

I have Added screenshots of the three .md file @Vikash-8090-Yadav  sir.

**Review by Vikash-8090-Yadav — APPROVED** [review]

**Review by Vikash-8090-Yadav — COMMENTED** [review]
delete  line  10 and 11 of the add-project,md file  and  in  place of these lines add ->

**Project title**
(Write project title over here)

**Project Description**
(Describe the project over here)

**Comment by surjyaneeh** [comment]
> delete line 10 and 11 of the **add-project,md** file and in place of these lines add ->
> 
> **Project title** (Write project title over here)
> 
> **Project Description** (Describe the project over here)

Done @Vikash-8090-Yadav  sir, anything more?

**Comment by Vikash-8090-Yadav** [comment]
Look's great !

**Pull request merged**
