### PR TITLE
Readme file add

### PR DESCRIPTION
**Pull request by kunal232i**
Done the changes according  to https://github.com/Vikash-8090-Yadav/Web3.0-World/pull/36#issuecomment-1221293889 😄

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
@kunal232i  also do the  changes in the Main level 0 readme

**Comment by Vikash-8090-Yadav** [comment]
@kunal232i  ??

**Comment by Vikash-8090-Yadav** [comment]
@kunal232i  complete this issue asap .

**Comment by kunal232i** [comment]
Done with the issue have look at it now..

**Comment by kunal232i** [comment]
> @kunal232i complete this issue asap .

Done with the issue have a look at it now.

**Comment by Vikash-8090-Yadav** [comment]
Great work @kunal232i  .

**Pull request merged**
