### PR TITLE
styled form -LEVEL 0 SendToEather

### PR DESCRIPTION
**Pull request by iamifechi**

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Share the ss also @iamifechi

**Comment by iamifechi** [comment]
@Vikash-8090-Yadav pls what is ss?

**Comment by Vikash-8090-Yadav** [comment]
@iamifechi Screen shot

**Comment by iamifechi** [comment]
@Vikash-8090-Yadav ok here, how's this
127 0 0 1_5500_Web3 0-World_Level0_SendToEather_
?

**Comment by Vikash-8090-Yadav** [comment]
Graet @iamifechi

**Pull request merged**
