### PR TITLE
Iwoc logo

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
Done with the changes

### CODE REVIEW

**Comment by Bharadwajshivam28** [comment]
@Vikash-8090-Yadav BY mistake sir those branches were deleted so i have done changes in new branch

**Comment by Vikash-8090-Yadav** [comment]
i guess u have done something wrong ,  all the images are showing in the vertical format . the middle  one are in horizontal. so if u r facing  problem i will suggest u to close this pr . forrk my repo again in new folder and firstly do  the readme part . just by doing copy pasting . as  i already assigned u that all  image task  so no  one is going to take that !!

**Comment by Bharadwajshivam28** [comment]
sir i have done the readme part

**Comment by Bharadwajshivam28** [comment]
sir the readme file is done that also should i close pr and do again in new fork

**Comment by Bharadwajshivam28** [comment]
or can i copy paste this readme into new one by forking and all

**Comment by Bharadwajshivam28** [comment]
> i guess u have done something wrong , all the images are showing in the vertical format . the middle one are in horizontal. so if u r facing problem i will suggest u to close this pr . forrk my repo again in new folder and firstly do the readme part . just by doing copy pasting . as i already assigned u that all image task so no one is going to take that !!

ok sir

**Pull request closed without merging**
