### PR TITLE
DOCS: SSOC logo added in README

### LINKED ISSUE #41: Add SSOC LOGO
Hey folk's hop u  all are doing well in this  issue  you all have to attach the SSOC logo just after t the HSOC 
The  logo  is given below adjust the height and width accordingly . 
Thank u 
IMG-20220820-WA0008

### PR DESCRIPTION
**Pull request by chirag0002**
SSOC logo added in the Section of associated open source programs.

Web3 0-World_README md at 61d8ceb901aaf448ea129cc5168d5af862e8b03c · Vikash-8090-Yadav_Web3 0-World - Brave 22-08-2022 12_49_52 (2)

closes #41

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
@chirag0002  give a space between  them and also remove the box forming

**Comment by Vikash-8090-Yadav** [comment]
@chirag0002  any updates

**Comment by chirag0002** [comment]
I was little busy, but it will be done by tomorrow!!

**Comment by chirag0002** [comment]
Hey @Vikash-8090-Yadav , is it okay ?

added more communities and OSS project by chirag0002 · Pull Request #166 · commclassroom_roadmaps - Brave 25-08-2022 21_50_22 (2)

**Comment by Vikash-8090-Yadav** [comment]
@chirag0002  Good . Looking forward for your more contribution

**Pull request merged**
